title:              저길 봐, 작은 점 하나 너하고 내가 살던 별이야
email:              maker_augustleo@kakao.com
description:        한 번도 넌 떠나본 적이 없었지, 아마 더 큰 용기가 필요하겠지
author:             Leo Kim   
url:                "https://maker-augustleo.github.io"

# Social Profiles
twitter_username:   llleeo0421
github_username:    August-leo-0805
instagram_username:  llleeo0421
linkedin_username:  augustleo

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
